### ISSUE TITLE
A bug for mode change.

### ISSUE THREAD

**Issue by NB-Dragon** [NB-Dragon/AdvancedDownloader#4]
这里记录一下，当第一次运行出现单线程，第二次运行出现多线程，由于文件part1丢失导致的意外终止

**Comment by NB-Dragon** [comment]
目前进度为提出问题，暂未有相关报错日志进行分析。
如有碰到这个问题的，欢迎分享相关错误日志，以便定位并解决问题。

**Comment by NB-Dragon** [comment]
添加异常信息
```
Traceback (most recent call last):
  File "AdvancedDownloader/main.py", line 44, in <module>
    DownloadHelper(message_queue, url, save_path, download_index, headers, cookies)
  File "AdvancedDownloader/tool/DownloadHelper.py", line 14, in __init__
    self._create_download_mission()
  File "AdvancedDownloader/tool/DownloadHelper.py", line 22, in _create_download_mission
    http_helper.start_download_mission()
  File "AdvancedDownloader/schema/HTTPDownloader.py", line 145, in start_download_mission
    self._listen_download_message()
  File "AdvancedDownloader/schema/HTTPDownloader.py", line 309, in _listen_download_message
    if self._check_file_in_normal_region(download_queue_key):
  File "AdvancedDownloader/schema/HTTPDownloader.py", line 322, in _check_file_in_normal_region
    current_size = os.path.getsize(each_download_queue["filename"])
  File "Anaconda3/lib/python3.7/genericpath.py", line 50, in getsize
    return os.stat(filename).st_size
FileNotFoundError: [Errno 2] No such file or directory: 'AdvancedDownloader/clash-1.2.0/clash-1.2.0.zip.part1'
```
