### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by GodDai** [NB-Dragon/AdvancedDownloader#5]
macos 10.15
python -m venv 新建了一个环境内
执行python main.py 报错
[尝试过网上的方案](https://blog.csdn.net/mouday/article/details/96379223)均无效
```
Traceback (most recent call last):
  File "main.py", line 3, in <module>
    from tool.DownloadHelper import DownloadHelper
  File "/Users/heletian/Documents/Tool/AdvancedDownloader-0.3.5/tool/DownloadHelper.py", line 1, in <module>
    from schema.HTTPDownloader import HTTPDownloader
  File "/Users/heletian/Documents/Tool/AdvancedDownloader-0.3.5/schema/HTTPDownloader.py", line 12, in <module>
    from tool.CurlHelper import CurlHelper
  File "/Users/heletian/Documents/Tool/AdvancedDownloader-0.3.5/tool/CurlHelper.py", line 7, in <module>
    import pycurl
ImportError: pycurl: libcurl link-time ssl backends (secure-transport, openssl) do not include compile-time ssl backend (none/other)

```

**Comment by NB-Dragon** [comment]
我看你的提示里面，相比于网上的攻略，多了一个secure-transport，是不是系统环境做了限制？

**Comment by NB-Dragon** [comment]
可以试试[这个](https://www.cnblogs.com/Fushengliangnian/articles/11341927.html)方案

**Comment by GodDai** [comment]
谢谢 博主 无奈都试过了 没办法 我也不知道为啥 我甚至在python执行的时候都加上sudo 依旧这个报错 应该不是权限问题

**Comment by NB-Dragon** [comment]
网上的方案基本上跟“secure-transport”这个提示无关，你的情况应该是非常特殊的。
我怀疑是系统限制，或者运行环境丢失造成的。
后面会考虑抛弃pycurl，看看是否有人愿意提供资金支持吧，哎，最近写代码都有心无力了
